### PR TITLE
Improve logo for navbar & footer

### LINKED ISSUE #23: Logo in navbar
Do not use a logo, use cynkra text + a dot as on cynkra.com (it'll probably work without needing to add CSS rules since we already have those for the footer).

### PR DESCRIPTION
**Pull request by maelle**
Fix #23 

- Added cynkra as svg in the navbar and footer.
- Added corresponding CSS rules.
- Removed useless files.

### CODE REVIEW

**Comment by maelle** [comment]
Are we okay with the non perfect alignment of the text and blue square? It's also the case on the current cynkratemplate.

image
image

**Comment by maelle** [comment]
Removed the boldness since the font is not designed for being bold.

**Comment by christophsax** [comment]
No, not ok ;-)

The website does that: `font-weight: 800; letter-spacing: 1.76`. And some extra margin adjustment for the dot.

image

**Review by pat-s — COMMENTED** [review]
@maelle https://github.com/cynkra/tv/blob/gh-pages/extra.css#L186-L194 might help. I don't think we can get around a dedicated CSS class for the dot 🙂

**Comment by maelle** [comment]
Thanks all!

On https://tv.cynkra.com/ the dot is text, but on the website it's an image so I'm going for that as it might make it easier to copy the website look.

Is there a guideline, or sould I define one (by measuring), that'd state, _relative to font size_ (a percentage maybe?),
- the acceptable font weight,
- the acceptable letter-spacing,
- the size of the dot compared to the letter a (50%),
- the space between the letters and the dot.

On the website the font for the logo at the top left is still frutiger light, not another one, from what I see, and I can't find a reference to another font in the web repo. I might be missing something. :sweat_smile:

**Comment by maelle** [comment]
Or maybe we can decide to use an _image_ of the logo anywhere else that isn't the website, and simply make sure to respect the width/height ratio, that might be simpler.

**Comment by maelle** [comment]
Although that might not be ideal either since there are places where the text on the logo should be aligned with text on the same line :sweat_smile:

**Comment by pat-s** [comment]
I think for most of your questions I'd say: just choose what you think is the best solution going forward :) we can then discuss it in more detail. You might have lot more experience in such things than us 😄

We have no existing rules on relative margins or similar things in our template. But we could definitely create some and briefly document them :)

**Comment by maelle** [comment]
Maybe this could be decided and then put in the notes on visual identity (happy to help summarize those + implement them in cynkratemplate).

**Comment by pat-s** [comment]
I guess @christophsax would be interested in defining visual identity rules :)

**Comment by maelle** [comment]
@christophsax I've now updated this PR to use an SVG (created from a PDF) as I think it's a sustainable choice (more straightforward than CSS rules to tweak text).

image

image

The logo near the top of the README (not the one from the navbar) might be nicer with some sort of frame (dare I say, hex frame? :innocent: ).

**Comment by maelle** [comment]
preview https://cynkra.github.io/cynkratemplate/

**Comment by christophsax** [comment]
Is there a preview?

> might be nicer with some sort of frame

It's pretty like this. We don't use a frame / or hex frame anywhere, so no need to start here ;-). 

Should there be a bit of extra space between the cynkra logo and 'cynkratemplate' in the navbar?

Frutiger is too complicated? Don't think its a dealbreaker, but wasn't that on of the key points of the project?

But if in doubt, I would opt for realease and fix as we move along.

**Comment by maelle** [comment]
I mean it's easier to move an svg around and to just change its size/padding rather than having to use the css rules related to font family, weight, etc.; but I am not sure I am right. :sweat_smile:

**Comment by christophsax** [comment]
And I see Frutiger here, very nice:

image

**Comment by christophsax** [comment]
image

I think this would look prettier if the cynkra logo is *above* the title cynkratemplate. Or do we need it at all?

**Comment by maelle** [comment]
> And I see Frutiger here, very nice

Yes, thanks to @pat-s allowing access from that URL. :pray: 

> I think this would look prettier if the cynkra logo is above the title cynkratemplate. Or do we need it at all? Having the logo twice may be a bit of an overkill?

Good idea, now removed!

Fine to merge?

**Comment by christophsax** [comment]
It's very nice and, in principle, it is ready to merge.

Since I can now browse the preview, I saw a few tiny details:

- [ ] Remove the dot after the logo (not the blue one, the one that marks the end of the sentence), and the 'Visit us at www.cynkra.com'. It's obvious that one can click on the logo.
    image
- [ ] Similarly, I would drop the cynkra Consulting button. We want to sponsor Opens source, and not primarily using it a mean for selling our stuff. The more understatement, the better, i.m.O. This solves the problem that the margin between the buttons is too small.
    image
- [ ] More horizontal space after the dot of the cynkra logo: e.g., `cynkra.   < 5px >   cynkratemplate`
    image
- [ ] This is cynkrablue, right? Nice. But it should use white not black as a contrasting color:     
     image


Otherwise, very enjoyable. Thanks a lot!

**Comment by christophsax** [comment]
Very nice! Thanks!

**Comment by krlmlr** [comment]
Weird, I don't see a logo at https://cynkra.github.io/cynkratemplate/, only a plain-text link.

Screen Shot 2022-10-04 at 05 03 00

**Pull request merged**
