### PR TITLE
Change fonts url

### PR DESCRIPTION
**Pull request by wael-sadek**
Change fonts url to the main web.

### CODE REVIEW

**Review by krlmlr — APPROVED** [review]
Looks good to me, I tested a few of the links.

**Review by pat-s — COMMENTED** [review]
Nit-picking: do we want to have assets like fonts to live under `user/`? How about bundling them under `assets/`?

**Comment by krlmlr** [comment]
Good point, Patrick. Wael: Let's discuss and merge when we meet.

**Comment by maelle** [comment]
Another question: why are the filenames so "unreadable", are they likely to change? Asking because of https://github.com/cynkra/dm/pull/1872/

**Comment by krlmlr** [comment]
Duplicate of #42.

**Pull request closed without merging**
