### PR TITLE
bigger logo

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
There will be no preview because it's from a fork :woman_facepalming: 

image

**Comment by maelle** [comment]
I do not have write access to this repo actually.

**Comment by pat-s** [comment]
You should now have write access.

**Comment by pat-s** [comment]
WRT to the logo:

image

Imo the icon is too big, i.e. it does not play well with the font size of the package name and the white background looks off (which might be a problem of the logo in fact).

The current one is of course too small. I am not sure why the current version is so small. I like the one in https://tv.cynkra.com/ much more as it aligns with the height and font-size of the package name. What do you think?

The tv package was also created by cynkratemplate sources (at least at one point).

**Comment by maelle** [comment]
Indeed, in the end in #23 I started thinking it should be like in the footer so not an image but actual letters with the font rules.

**Pull request closed without merging**
