### PR TITLE
Update font links

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks!

**Comment by wael-sadek** [comment]
> The pkgdown site has been rebuilt, still the font hasn't been updated on https://dm.cynkra.com/ or https://dm.cynkra.com/dev.
> 
> Seems that the right cynkratemplate version has been used in that build: https://github.com/cynkra/dm/actions/runs/5311496713/jobs/9614953630#step:6:631 .
> 
> Do we need to do anything else here?

Still using the old version `v0.0.1.9004` a new tag is needed, is it generated by `cynkra/fledge` ?

**Comment by krlmlr** [comment]
Not sure, but I created v0.0.1.9005 and restarted the process: https://github.com/cynkra/dm/actions/runs/5312172894/jobs/9616326676 .

**Comment by wael-sadek** [comment]
> Not sure, but I created v0.0.1.9005 and restarted the process: https://github.com/cynkra/dm/actions/runs/5312172894/jobs/9616326676 .

Thanks @krlmlr , looks like it's fixed now.
I see few errors though
```
https://dm.cynkra.com/favicon-32x32.png
https://dm.cynkra.com/favicon-16x16.png
```
404 responses for the above.

**Pull request merged**
